index.js
=> bugfix(point): fill should use ol.style.Fill

index.js
Pull request to address first issue of https://github.com/boundlessgeo/ol-mapbox-style/issues/18
=> Updating spriteRegEx to accept any parameters in sprite URL

index.js
=> Allow passing in json for the style parameter

index.js, test/test.js
=> Handle visibility on tile layers

index.js
See https://github.com/boundlessgeo/ol-mapbox-style/issues/30
=> Fallback to normal resolution if @2x spritesheet is not found (#30)

index.js, package.json, test/test.js
And fix the reported errors
fixes #45
=> Run eslint on the code

Jenkinsfile
=> Add CI integration

Jenkinsfile
Seemed SonarQube was doing a Java analysis and failing, trying to set it javascript explicitly to see if that works
=> Set the sonarqube language

Jenkinsfile
=> Have coverage run on the right files

Jenkinsfile
=> Do not analyze coverage subdir

.npmrc, __tests__/test.js, index.js, package.json
One test is still failing need to figure out why (update: resolved now)
=> Upgrade to openlayers 5

index.js
For [#75](https://github.com/boundlessgeo/ol-mapbox-style/issues/75)
=> add 'resolutions' parameter

stylefunction.js
Do not clear filter and function cache with every stylefunction call.
=> Fix filter/function cache performance issue

.babelrc, example/data/geojson.json, example/data/states.json, index.js, package.json, stylefunction.js
This pull request brings the long awaited support for style and filter expressions. See https://blog.mapbox.com/announcing-expressions-in-gl-js-a72b55d0a6af.
=> Support gl expressions

index.js, stylefunction.js
Reverts boundlessgeo/ol-mapbox-style#92
=> Revert "Change imports for mapbox-style-spec"

README.md, __tests__/applyStyle.test.js, __tests__/finalizeLayer.test.js, __tests__/fixtures/style-empty-sprite.json, __tests__/fixtures/style-invalid-sprite-url.json, __tests__/test.js, babel.config.js, example/stylefunction.js, index.js, package.json, stylefunction.js
This pull request fixes several issues with the tests, improves the API docs, and makes the library easier to use thanks to more consistent promise rejections and errors thrown.
=> Improve docs, error handling and tests

__tests__/applyStyle.test.js, __tests__/finalizeLayer.test.js, __tests__/stylefunction.test.js
Cosmetic simplification of the test suite.
=> Use should directly

stylefunction.js
Remove a unnecessary line already declared.
=> remove unnecessary line

stylefunction.js
This pull request adds support for the `icon-rotation-alginment: 'map'` property.
=> Icon rotation alignment

__tests__/test.js, index.js, webpack.config.olms.js
This pull request adds support for `bounds` in TileJSON, raster and vector sources.
=> Add support for layer bounds

.circleci/config.yml, README.md, test/karma.conf.js
This pull request fixes the circleci setup.
=> Continuous integration with CircleCI

stylefunction.js
Add support for https://docs.mapbox.com/mapbox-gl-js/style-spec#layout-symbol-text-letter-spacing
will fix https://github.com/openlayers/ol-mapbox-style/issues/137
=> Add text-letter-spacing support

stylefunction.js
=> Fix color handling for zero opacity

example/index.html, example/openmaptiles.js
=> Add an OpenMapTiles example

index.js, stylefunction.js, test/index.test.js
=> Remember when fonts have been loaded already

example/_template.html
Tested with browserstack.com 
closes #42 
closes #43
=> Add polyfill.io script for IE11 compatibility

index.js, test/fixtures/background.json, test/index.test.js
`style.opacity` instead of `style.backgroundOpacity`.
=> Fix wrong CSS property for background-opacity

index.js, test/index.test.js
=> Respect source minzoom also from TileJSON

package.json, stylefunction.js, test/stylefunction.test.js
Fixes #170.
Note: To render lines with the correct height, OpenLayers v6 is required.
=> Add support for line-height and respect halo for text anchor

index.js, test/index.test.js
=> Load google fonts with correct weight and style

stylefunction.js, test/stylefunction.test.js
=> Support text-max-angle

util.js
This pull request improves line breaks for multi-line text.
=> Set higher threshold for short lines

index.js
This pull request avoids layer creation for unsupported types.
=> Do not create layers for unsupported types

stylefunction.js
=> add text-translate

stylefunction.js
=> Fix performance issue by caching circle-related style

.npmignore
The package broke with #189. This pull request fixes it.
=> Fix package with proper .npmignore

stylefunction.js
=> add text-rotation-alignment

package.json
This was meant to be merged with #203.
=> Use OpenLayers with new z-index order

stylefunction.js
=> add icon-anchor

index.js
With this change, `vector` layers that use the same `source` in the Mapbox Style document also share the source in OpenLayers. Previously, a new OpenLayers source was created for each layer.
=> Reuse vectortile sources acrosss layers

index.js
=> Support mapbox urls for all layer types

examples/stylefunction.js, package.json, src/olms.js, test/index.test.js, webpack.config.examples.js
=> Fix legacy build

README.md, jsconfig.json, src/index.js, src/stylefunction.js, src/util.js, tsconfig-typecheck.json
This pull request makes `stylefunction` work in workers.
=> Worker support for stylefunction

package.json, src/stylefunction.js
=> Peg @mapbox/mapbox-gl-style-spec to a specific version

test/util.test.js
This pull request adds more text wrap tests.
=> More tests

webpack.config.olms.js
=> Add ol.style.Text to externals

src/index.js, src/stylefunction.js
=> Flatten 3d by treating fill-extrusion as fill

README.md
Correct the `stylefunction` import path in the example snippet
=> Correct import path in example snippet

src/index.js
This pull request adds a function that OpenLayers will be using for creating a MapboxVectorTile layer from a gl source with a TileJSON url.
=> Add private export for building a TileJSON source from ol/layer/MapboxVectorTile

tsconfig-build.json
=> Publish auto-generated .d.ts files

src/stylefunction.js
OpenLayers now supports icon coloring, so we can rely on OpenLayers's functionality here.
Fixes #324.
=> Fix icon-color handling

src/index.js
This pull request fixes relative TileJSON urls and adds the missing absolute style url to the TileJSON cache key.
=> Fix tilejson urls and cache

src/index.js, test/index.test.js
=> Attempt to detect default view

src/stylefunction.js
This pull request adds support for the `icon-offset` layout property.
=> Add support for icon-offset

README.md, package-lock.json, package.json, src/index.js, src/stylefunction.js
This pull request adds support for rich text labels using the [`format` expression](https://docs.mapbox.com/mapbox-gl-js/example/display-and-style-rich-text-labels/). This requires OpenLayers >= 6.13 (or a recent 6.12-dev version).
=> Add support for rich text labels

README.md, examples/data/geojson.json, examples/geojson-featurestate.js, examples/index.html, src/index.js, src/stylefunction.js, test/index.test.js, test/stylefunction.test.js
This pull request adds support for `feature-state`, including two new functions (`setFeatureState()` and `getFeatureState()`).
Replaces and closes #201.
=> Add support for feature-state

src/apply.js, test/apply.test.js
This pull request fixes a regression that causes all layers of a sources being added to an OpenLayers layer, instead of just those that match the respective part of the layer stack.
=> Fix layer stacking regression

src/util.js
=> Accept application/json when requesting json

examples/data/geojson.json, examples/geojson-featurestate.js, src/apply.js, webpack.config.examples.cjs
This pull request fixes handling of relative sour url handling for GeoJSON layers, and modifies the examples to work from arbitrary urls.
=> Fix relative source url handling

src/stylefunction.js
=> Simplify template handling and make it more secure

CHANGELOG.md, PUBLISHING.md, package-lock.json, package.json
Changes for the 8.2.1 release.
=> Changes for 8.2.1

PUBLISHING.md
This reverts commit cd5c2bcf38bad94c99599b90d4f24d7aa835684b.
=> Revert "Add a step to the publishing doc"

src/stylefunction.js
Support text-justify, fixes #645
=> add support for text justify

CHANGELOG.md, README.md, package-lock.json, package.json, src/stylefunction.js
=> Icon offset updates for v7 and x-direction fix

src/apply.js, test/applyStyle.test.js
=> Allow all options in applyStyle's 3rd argument

src/util.js, test/util.test.js
This reverts commit 4606f6cd4414d129e41d7ea60f7d33931ab644d7.
Fixes #735
=> Fix Mapbox tile URL regression

examples/geojson-wfs.js, src/apply.js, test/apply.test.js
=> Fix bbox parsing when using transformRequest

examples/geojson-wfs.js
Addresses https://github.com/openlayers/ol-mapbox-style/pull/754#discussion_r1055604847.
=> Remove unnecessary transformRequest

examples/data/geojson-inline.json, src/stylefunction.js, src/util.js
This pull request makes the recently introduced icon halo more pronounced and look the same as the text halo.
=> Improved icon halo

src/apply.js, test/apply.test.js
=> Fix addMapboxLayer

README.md, src/apply.js, test/apply.test.js
For convenience, in conjunction with `addMapboxLayer()` and `updateMapboxLayer()`, this pull request adds a `removeMapboxLayer()` function.
=> Add removeMapboxLayer function

src/apply.js, test/apply.test.js
=> Set OpenLayers layer visibility to false when no layers are visible

examples/data/geojson-wfs.json, src/stylefunction.js
This pull request adds support for the "id" expression.
=> Add support for the "id" expression

src/apply.js
This pull request fixes the problem that vector and geojson layers were visible before the style was applied, resulting in unnecessary rerender and an initial rendering without style.
=> Fix initial layer visibility

src/util.js
=> Fix full build by fixing getUid import

src/util.js, test/util.test.js
=> Make updateMapboxStyle work with new object literals

src/apply.js, src/util.js, test/apply.test.js
This pull request adds support for the TMS tile schema, using the `scheme: 'tms'` source option.
Fixes #862
=> Add support for the tms tile scheme

src/util.js, test/util.test.js
See #917.
This pull request does not fix the underlying issue, but it removes the restriction that a layer cannot be inserted as first layer.
=> Match added layer to source of any adjacent layer

src/util.js
This pull request fixes a regression that prevented add/update/removeMapboxLayer to work with non-vector(tile) layers. In addition, it makes sure that a removed layer also gets removed from the layers arg that's passed to `stylefunction()`.
=> Small fixes for add/update/removeMapboxLayer

README.md, src/apply.js
This pull request updates the type of the applyBackground function.
=> Fix type of applyBackground args

src/mapbox.js, test/mapbox.test.js
=> Do not overwrite existing search param with key accessTokenParam

src/stylefunction.js, test/stylefunction.test.js
Fix issue #1067
Sorry for taking so long to submit this PR.
My English is not very good， maybe some rewording is needed.
=> Don not match layer ids to string  in stylefunction

src/stylefunction.js
=> Fall back to default icon-color when drawing SDF

package-lock.json, package.json
Avoids problems when combining ol-mapbox-style with ol@dev versions.
=> Generous peer dependency range for ol

src/apply.js
=> Use point resolution for hillshade calculation

src/apply.js, test/apply.test.js, test/applyStyle.test.js
=> Fix layer minzoom

README.md, src/apply.js, test/apply.test.js, test/stylefunction.test.js
=> Add webfonts option to override ol:webfonts

src/util.js
This pull request makes ol-mapbox-style web worker friendly again.
=> Avoid document.createElement

package-lock.json, src/MapboxVectorLayer.js
=> Use ol v10 type generics for MapboxVectorLayer

src/stylefunction.js
Fixes a bug to have the textField reduce function return the accumulator in all cases. Fixes #1217
=> Update stylefunction.js to fix textField reduce function

src/stylefunction.js
Following up on #1250, this makes a Response also work for the SpriteImage.
=> Support Response for spriteImageUrl

examples/mapbox.js, package-lock.json, package.json, src/apply.js, src/stylefunction.js, src/util.js, test/stylefunction-utils.test.js
=> Handle 'pitch' and 'distance-from-center'

src/text.js
Firefox sometimes stores fonts in a FontFace with leading and trailing quotes, so we need to normalize that. And to safeguard against different case on the font family name used in the `@fontface`, we should compare font family names in lowercase.
=> More font loading improvements
