openlayers/ol-mapbox-style

index.js

This applies possible opacity and rotation values defined in the Mapbox style to the ``ol.style.Icon`` object.
The assignment is done outside the caching object (``iconImageCache``) by purpose to ensure an icon can be reused with different opacity and rotation values.

Apply opacity and rotation to icon style

---

index.js

Apply the Mapbox style property ``icon-size`` to the corresponding OpenLayers style object.
The icon-size can be set as number or as function and is multiplied with the perviously used ``spriteScale`` value.

Add support for icon-size

---

index.js

There was no support for doing basic 'Points as Circles' rendering.  This adds support for the Mapbox GL styles that allow the user to configure those.

Added support for circle styles

---

package.json

To make the build script runnable on Windows systems the native ``mkdir`` command in the ``prepublish`` script is replaced by the npm module ``mkdirp``, which runs cross-platform.

Use mkdirp module to create dist folder

---

index.js

In our React component we setTarget(null) on unmount of the component, however this causes an error in the background logic of ol-mapbox-style. This change protects the code against having no map target anymore.

Do not fail on setTarget(null)

---

index.js
package.json

At the moment, if there is a source (`type: vector`) with high `minzoom` (e.g. 9) and the map is positioned to view the whole world, OpenLayers tries to load all the tiles covering the extent (it's a lot of tiles for z9 :-) ) and the browser crashes (I even had to force-restart my computer in one case).
This PR adds maxResolution to the layers where sources have `minzoom` > 0 so the rendering of such layers is skipped until appropriate. This behavior is consistent with mapbox-gl-js.

Fix browser crash for sources with high minzoom

---

index.js

This fixes a rare case. When using `olms.apply` with existing Map object with a style that does not have `center` and `zoom`, the map view is incorrectly reset.

Respect existing map view

---

index.js
package.json

1. Converts the XHR calls for sprites to fetch.
- Makes testing in other apps easier.
- Creates a consistent Promise-based request chain.
2. Added 'isomorphic-fetch' dependency to shim for fetch
when it is missing from the environment.
refs: #41

Convert XHR calls for sprites to fetch

---

index.js
test/test.js

This is a follow-up to #50 we found out in our setup that sprite calls were now failing, this is because it's not passing on the credentials
Also fixed a failing test because the tegola file does not have attribution anymore.

Fetch should pass on credentials

---

index.js

Fixes the same typo as #49 but now in the source and not in the generated file

Fix typo in comments, which is used for README generation

---

index.js

It seems that there are missing attributions on sources constructed with `processStyle` since https://github.com/openlayers/openlayers/pull/7329.
The `ol.source.TileJSON#getAttributions()` always returns null at the moment.
This PR fixes this temporarily until the next major release of OpenLayers.
It should be forward-compatible.

Fix missing attributions on constructed sources

---

.npmignore

This will prevent the .babelrc from being in the node_modules
tree.

Add .babelrc to npm ignore.

---

stylefunction.js

This fixes the sdk paint change example for now
We will need to revisit this when we add the diffing.

Clear cache when applyStyle gets called again

---

stylefunction.js

For https://github.com/boundlessgeo/ol-mapbox-style/issues/82

Add support for fill-pattern

---

stylefunction.js

Currently the closure for `img.onload` keeps a reference to `olLayer`. This prevents OpenLayers Map from being garbage collected even if the Map is not used anywhere else. The full retaining path looks something like this:
```
OpenLayers shared IconImageCache -> IconImage -> img in this project -> onload closure -> layer -> ... -> Map. 
```

Avoid keeping a reference to the OpenLayers Map

---

index.js
stylefunction.js

Currently, this module imports ES6 code directly from the mapbox-style-spec module. This makes it difficult to use in projects that do not transpile the node_modules directory.
This PR imports from the built ES5 code in the mapbox module.

Change imports for mapbox-style-spec

---

index.js
stylefunction.js
webpack.config.js
webpack.config.olms.js

This pull request replaces #92.
The downside is that all bundles created from `ol-mapbox-style` will be larger by 10 kB than with the source imports we previously used.
For `create-react-app` users, we should consider making that work with ES modules, which it maybe already does in the latest alpha version. See facebook/create-react-app#3889.
That said, I'm not sure if we want to merge this. @bartvde @frankrowe what do you think?

Use transpiled imports from mapbox-gl-style-spec

---

package.json

When I tried to run the tests, I was getting the following error during build:
```
> ol-mapbox-style@3.0.1 build /Users/fleur/work/rug/ol-mapbox-style
> webpack-cli --config ./webpack.config.olms.js && webpack-cli
/Users/fleur/work/rug/ol-mapbox-style/node_modules/webpack-cli/bin/config-yargs.js:89
describe: optionsSchema.definitions.output.properties.path.description,
^
TypeError: Cannot read property 'properties' of undefined
at module.exports (/Users/fleur/work/rug/ol-mapbox-style/node_modules/webpack-cli/bin/config-yargs.js:89:48)
at /Users/fleur/work/rug/ol-mapbox-style/node_modules/webpack-cli/bin/webpack.js:60:27
at Object.<anonymous> (/Users/fleur/work/rug/ol-mapbox-style/node_modules/webpack-cli/bin/webpack.js:515:3)
at Module._compile (internal/modules/cjs/loader.js:689:30)
at …
```

updated webpack & webpack-cli to current versions

---

stylefunction.js

Add `circle-stroke-opacity` style than `circle-opacity` style.
https://www.mapbox.com/mapbox-gl-js/style-spec#paint-circle-circle-stroke-opacity

Add circle stroke opacity style

---

stylefunction.js

When a layer type is `fill`, it occur `Uncaught TypeError: Cannot read property 'type' of undefined` error in the `getValue`.

Reassign the layer type check point for line.

---

__tests__/applyStyle.test.js
__tests__/stylefunction-utils.test.js
stylefunction.js

I'm writing tests as I'm learning the codebase, if you'd like to incorporate them.  I inadvertently checked in a bit of code tightening up I did in `__tests__/applyStyle.test.js`, which aren't needed.  I can remove that if you like.  Also minor error handling improvement to `getValue()`.

added tests for some utility functions defined in stylefunction.js

---

index.js

This pull request removes the z-index from the OpenLayers layers that the library creates. This improves interoperability in cases where users add layers to their map that are not handled by the library.
Fixes #119.

Do not set z-index on layers

---

index.js
stylefunction.js

Currently we limit the zoom levels more than the style spec does. With this pull request, we support the full zoom range up to z24. For the view, we now make sure that we do not go beyond that.

Allow zoom levels according to the style specification

---

README.md
index.js
test/index.test.js

There are situations where applications need all the layers that `ol-mapbox-style` created from a `sources` entry of the Mapbox Style document. This pull request adds a `getLayers()` function for this purpose.

Add getLayers utility function

---

stylefunction.js

Would fix part of https://github.com/openlayers/ol-mapbox-style/issues/137
Text-padding should be a number, as defined in the [Mapbox spec](https://docs.mapbox.com/mapbox-gl-js/style-spec#layout-symbol-text-padding) so it is converted to an array as wanted in [OL spec](https://openlayers.org/en/latest/apidoc/module-ol_style_Text-Text.html)

Add text padding support

---

index.js
test/index.test.js

This pull request is a replacement for #143 and fixes more underlying issues of the `getLayer()`, `getLayers()` and `getSource()` function. The `indexOf` check does not make sense for `getSource()` and `getLayers()` because the `mapbox-source` property of the layer is a string, not an array. And for `getLayer()`, the fix proposed by @RobertOrthofer in #143 needs to be applied.
Thanks @RobertOrthofer for inspiring this change.

Fix getSource, getLayer and getLayers

---

stylefunction.js

If the text cannot be split, return it without computing its width.

Optimize wrapText function

---

CHANGELOG.md
index.js
stylefunction.js
test/fixtures/hot-osm/hot-osm.json
test/index.test.js
util.js
webpack.config.olms.js

Previously `minzoom` and `maxzoom` handling for sources (TileJSON properties) and layers was handled inconsistently. This change makes it so zoom levels for `layers` always refer to mapbox-gl zoom levels and zoom levels for TileJSON refer to zoom levels as defined by the tile size (i.e. the same as mapbox-gl for tile size 512, one off for tile size 256).
When `apply` or the default export are configured with a target element instead of an `ol/Map` instance, the view that ol-mapbox-style creates for the OpenLayers map also has the mapbox-gl resolutions. So `ol/View#getZoom()` will now report the same zoom level as mapbox-gl.
Both changes can be considered breaking changes in some scenarios, so I will bump the major version after this change.

Fix zoom, minzoom and maxzoom handling

---

stylefunction.js

Fixes #139.
Performance is improved for polygons with an outline, probably weighing out the performance penalty for polygons without an outline.

Always add stroke to fills, without a separate style

---

stylefunction.js

When a style defines a `fill-outline-color` with a zero opacity, it means that the user wanted to have no outline. So we need to stroke the polygon with the same color as its `fill-color`. This produces less garbage than conditionally creating polygon styles with or without a `Stroke`.

Handle fill-outline-color with zero opacity

---

stylefunction.js

And return sooner if the color or the layer's opacity is 0.

Don't store transparent colors in the cache

---

index.js
test/fixtures/tilejson.raster.json
test/index.test.js

~~OpenLayers 6 is needed because of https://github.com/openlayers/openlayers/pull/9254~~
https://docs.mapbox.com/mapbox-gl-js/style-spec/#sources-raster-tileSize
Fixes #165.

Use the tileSize value from the raster source

---

stylefunction.js

OLMS tackle this feature by creating a ol/style/Stroke behind the text, this doesn't mimic CSS text-shadow (as seems to be implemented in Mapbox) because it doesn't count the shadowed text width.
This is an attempt to get closer to the CSS rendering with text-shadow used in Mapbox.

Text-halo : take text size into account

---

stylefunction.js

When `text-letter-spacing` is set, we need to take it into account for calculating line breaks to get a correct `text-max-width`.

Take letter-spacing into account for line breaks

---

stylefunction.js
util.js

* Try to avoid lines with less than 30 % of the max width
* Try to equally distribute filled space across lines
* Clear measure cache when better font is available (ES modules only)
```
Freiburg im
Breisgau
```
instead of
```
Freiburg
im
Breisgau
```
or
```
United States
of America
```
instead of
```
United States of
America
```

Smarter text wrapping

---

stylefunction.js
test/stylefunction-utils.test.js

By returning color arrays from `colorWithOpacity()`, we forced OpenLayers to do a color translation to rgba, except for icon colors. With this change, OpenLayers can use the colors directly, and we do not need the cache any more.
Replaces and closes #182.

Use rgba colors and remove color cache

---

index.js
test/index.test.js

This pull request simplifies configuration when users want to create a custom map, but want ol-mapbox-style to be responsible for the view. For maps configured without a view, ol-mapbox-style will now replace the default view with a view with the correct resolutions, and apply center and zoom to it as if no map was provided.

Apply default resolutions also when map (but no view) is provided

---

stylefunction.js

When `text-letter-spacing` is set for a text, we use hair spaces to widen the text. This can cause sharp turns in text along lines. This pull request removes this effect by dividing the original label width by the label width after the hair spaces are applied.
Fixes #186.

Reduce max-angle when hairspaces are used

---

stylefunction.js
webpack.config.olms.js

By using render features instead of point geometries we can reduce build size and garbage when working with midpoints.

More efficient midpoint rendering

---

stylefunction.js
test/stylefunction-utils.test.js

This pull request changes the style spec import to import directly from the main module. As a result, the build size of bundles is reduced by about 90kB.

Only include style spec once

---

stylefunction.js

This pull request reduces pressure on OpenLayers's font cache: `CanvasRenderingContext2D` can only handle integer font sizes in pixels, so it makes no sense to use fractional font sizes.

Round text size to integer pixels

---

index.js
test/index.test.js

The font name was not correctly parsed if it contains more than two 'words'.

Fix Google fonts name parsing

---

index.js
test/index.test.js

Currently we configure a view with `resolutions`. By changing that so we configure `maxResolution` instead, we get the correct zoom levels for 512px tiles *and* a view that never shows more than one world.

Set maxResolution on view

---

stylefunction.js

Objects like `ResolvedImage` can result from `getValue`.
Stringify all return values from `getValue` before passing them to `fromTemplate` to prevent runtime errors.

Fix fromTemplate errors by only passing in Strings

---

src/util.js
test/util.test.js

Fix for issue #249 
When text is less than 30% and contains multiple words, `wrapText()` will attempt to append a next line, even if it does not exist. This PR adds a check to make sure there is a next line before combining.

Fix undefined line concatenation in wrapText util

---

src/util.js
test/util.test.js

This pull request fixes an issue that was introduced with #256, and changes `wrapText` so it preserves hard line breaks.

Preserve hard line breaks when wrapping text

---

src/stylefunction.js

This modifies the label midpoint to use the first midpoint for a MultiLineString and retains the existing functionality for LineString features.
This is the solution proposed in #95 to improve the labeling for MultiLineString features.
> To improve the situation, the easiest solution is to use getFlatMidpoint for LineString geometries and getFlatMidpoints with only the first midpoint for MultiLineString geometries. Anyone willing to provide a pull request?

Use first flatMidpoints when labeling MultiLineString features

---

src/util.js
test/util.test.js

Splicing on line 124 will update the array length. The additional decrement of length causes a bug where less than expected number wrapped lines will show. If the correct length is 1, this will even cause the label to not appear at all.

Fix removing too many lines when combining wrapped lines

---

README.md
src/index.js
src/olms.js
webpack.config.olms.js

Fixes https://github.com/openlayers/openlayers/issues/11103
Currently polyfills for Object.assign and String.prototype.startsWith are needed to use ol-mapbox-style on older browsers in addition to those required by OpenLayers.  olms already imports  `ol/obj#assign` via VectorLayer and VectorTileLayer and https://www.measurethat.net/Benchmarks/ListResults/3417 shows there is little if any performance advantage in using startsWith over indexOf for a single character on most browsers, and on Chrome it is considerably slower.

Make compatible with polyfill requirements for OpenLayers

---

src/util.js
test/util.test.js

Very short text with space like the house number '2 A' will get 'undefined' appended because both `prevWidth` and `nextWidth` are `Infinity` and the lines array is empty at that point.

Fix undefined appended for single line < 35% width

---

src/util.js

This PR addresses @mikeydunnx concerns in https://github.com/openlayers/ol-mapbox-style/pull/283
Practically undefined should not be appended anymore but better to be explicit about it.

Ensure text wrap array length > 1

---

src/index.js

This fixes incorrect tile urls generated by olms for the Esri OSM style https://www.arcgis.com/sharing/rest/content/items/3e1a00aeae81496587988075fe529f71/resources/styles/root.json
where neither the tile json path ends with / nor the tiles relative url starts with /

Ensure there is a / at join in tile urls

---

src/stylefunction.js
test/stylefunction.test.js

Fixes #311.
This pull request adds a new function, `recordStyleLayer()`. When called with `true`, features evaluated by ol-mapbox-style's style function will receive a new property, `mapbox-layer`, with the topmost layer that the feature belongs to.
This is useful when using hit detection, to know which filter matched or which style was applied.
```js
import { recordStyleLayer } from 'ol-mapbox-style/dist/stylefunction';
recordStyleLayer(true);
```
```js
const features = map.getFeaturesAtPixel(event.pixel);
if (features.length) {
const mapboxLayer = feature.get('mapbox-layer');
console.log(mapboxLayer.id);
}

Know which layer a feature belongs to

---

src/index.js
src/stylefunction.js
test/stylefunction.test.js

This pull request adds an optimization for rendering styles where an icon with an `icon-color` with zero opacity is defined. Such styles are often found in Esri vector tile caches. After this pull request, no image is created for such styles.

No icons with zero opacity

---

src/index.js

To be consistent with the `url` for `geojson` and `vector` layers, the `tiles` property for `raster` layers now also supports relative paths.

Support relative urls for TileJSON tiles

---

src/index.js
src/stylefunction.js
test/stylefunction-utils.test.js
tsconfig-typecheck.json

Importing the `es.js` files directly breaks non es builds.
Import by library name. That way it takes the appropriate module type.

fix: mapbox-gl-style-spec imports

---

src/index.js
src/stylefunction.js
test/stylefunction-utils.test.js
test/stylefunction.test.js

This pull request changes the scope of `filterCache` and `functionCache` to the `styleFunction`. This means that each `styleFunction()` invocation now has its own cache, avoiding cached functions or filters leaking into other styles.
I added @mike-000's test (159002509ed566cf97df88ebee9cb0be6db864be) from #375 to make sure that this pull request fixes the problem.
Supersedes and closes #375.
Fixes #390.

Cache scope

---

src/index.js
test/index.test.js

The upcoming OpenLayers version 6.10 will have a `background` property and a `setBackground()` function on VectorTile layers (openlayers/openlayers#13085). With this, it makes sense to modify the existing `applyBackground` function to accept a map *or* a layer as first argument.

Make applyBackground work on layers

---

.eslintrc
README.md
package-lock.json
package.json
src/olms.js
src/stylefunction.js
test/stylefunction.test.js

This pull request adds an option to render transparent content, e.g. invisible polygon fills, for hit detection. Example: when you want to have parcels rendered only with their outline, but want the whole parcel to be clickable, configure your style with
```json
"layers": [
{
"id": "parcel",
"source": "parcels",
"type": "fill",
"paint": {
"fill-color": "rgba(0, 0, 0, 0)"
}
}, {
"id": "parcel-outline",
"source": "parcels",
"type": "line",
"paint": {
"line-color": "rgb(0, 0, 0)",
"line-width": 0.5
}
}
]
```
In your application code, configure the new option:
```js
import { renderTransparent } from 'ol-mapbox-style/dist/stylefunction';
renderTransparent(true);
```
Fixes #108.

New renderTransparent() configuration option

---

src/stylefunction.js
test/stylefunction.test.js

When `renderTransparent(true)` is set, the color calculation fails because of a division by zero. This pull request changes things so when the alpha of a color is `0`, the css color `transparent` will be applied, instead of calculating a rgba value, which would cause a division by zero.

Fix rgba colors with zero opacity

---

package-lock.json
package.json
src/index.js

With openlayers/openlayers#13120, the private `options_` property of `ol/View` was removed, which we used in a hack to detect whether a view had modified defaults. Now that can be better handled by using `Object.assign(view.getProperties()...`. It's save to continue using the hack for users of older `ol` versions.

Use view properties (ol@>6.9)

---

src/index.js
test/fixtures/background-none.json
test/index.test.js

In cases where a background layer has `"visibility": "none"` for the layout, the background color and opacity should not be applied.
It looks like the current code handles the case where a map (with a target element) is passed to `applyStyle` but not the case where a layer is passed.

Avoid applying background if layout visibility is none

---

src/stylefunction.js
test/stylefunction.test.js

This pull request fixes the behavior when a fill-outline-color is set but no fill is rendered. In this case, the outline was previously not rendered. Now it is.

Allow outline stroke for polygons without fill

---

package-lock.json
package.json

With this pull request, fonts like `Inter Semi Bold` resolve correctly to a font weight of 600 (semi-bold).

Update mapbox-to-css-font to fix two-word font weights

---

src/stylefunction.js

This pull request makes `circle` styles work when no `circle-radius` is specified, by assuming the default of `5`.

Use default for circle-radius

---

src/index.js
src/stylefunction.js

Currently, vector and vector tile layers are treated differently: for the former, decluttering is off, for the latter, it is on. This pull request makes the behavior more consistent by adding decluttering also to vector layers. In addition, the `overflow: true` option is set for text styles, for better label placement on vector tile layers.

Declutter also vector layers, allow text overflow

---

README.md
examples/stylefunction.js
package-lock.json
package.json
src/index.js
src/olms.js
src/stylefunction.js
src/util.js
test/stylefunction-utils.test.js
test/stylefunction.test.js
tsconfig-typecheck.json
webpack.config.olms.cjs

This pull request aims for reducing the build size, by using individual modules from `@openlayers/mapbox-gl-style-spec` (temporary fork of `@mapbox/mapbox-gl-style-spec`). To make the modules consistent with the full build, all exports are now available from the main module.

Use modules from style spec

---

README.md
examples/esri-transformrequest.js
examples/index.html
jsconfig.json
package-lock.json
package.json
src/index.js
src/util.js
test/applyStyle.test.js
test/fixtures/osm-liberty/tiles.json

This pull request adds `Tile` as 4th resource type, so now also tile urls can be modified.
A new example, `esri-transformrequest.js`, shows how to make use of this.

Add transformRequest support for tile URLs

---

README.md
src/index.js
src/util.js
test/applyStyle.test.js

This pull request adds support for the `transformRequest` option for modifying requests for GeoJSON of a `geojson` source. To allow for more complex transforms than just modifying the URL, transforms for the new `GeoJSON` resource type may return `ol/source/GeoJSON` constructor options instead of a `Request` object.

Add transformRequest support for GeoJSON sources

---

.eslintrc
README.md
package-lock.json
package.json
src/index.js
src/olms.js
src/stylefunction.js
test/karma.conf.cjs
test/stylefunction-utils.test.js
tsconfig-typecheck.json
webpack.config.examples.cjs
webpack.config.olms.cjs

This pull request goes back to the `@mapbox/mapbox-gl-style-spec` package and creates bundles as small as possible.
This is a breaking change, because existing applications using imports other than `from 'ol-mapbox-style'` may not continue to work without modifications, depending on the used bundler.

Mapbox style spec direct import

---

README.md
examples/esri-transformrequest.js
package-lock.json
package.json
src/index.js
src/mapbox.js
src/stylefunction.js
src/util.js
test/applyStyle.test.js
test/mapbox.test.js
tsconfig-build.json
webpack.config.olms.cjs

This pull request improves the OpenLayers integration, with the goal of making `ol/layer/MapboxVector` very lightweight:
* Handle "first source" the same way as `ol/layer/MapboxVector` does
* Respect configured sources and modify them, instead of creating a new source
* Remove "source configuration" return type from the `transformRequest` option, because this can now be handled with a configured source.
* Provide Mapbox url utilities here, instead of relying on a circular OpenLayers dependency.
* Do not include transpiled sources in the bundle, instead do not minify the esm bundle for easier debugging.

Better OpenLayers integration

---

package-lock.json
package.json
src/stylefunction.js
src/text.js

This pull request removes the webfont-matcher dependency. Instead, Google fonts will only be loaded on demand, i.e. when they are not already available in the browser. In addition, a `sans-serif` fallback is added to all font strings, and "Arial Unicode MS" is replaced with "Arial" to match the common CSS name for the Arial font.
Fixes #448.

Google fonts without dependency and with better fallback/default

---

examples/esri-transformrequest.js
src/apply.js
src/util.js

By adding an `mapbox-source` property on sources created by ol-mapbox-style, we can avoid that sources are created twice. Transforming the source url only once allows proper caching in the TileJSON cache, which was previously useless when the `transformRequest` config option was used.

Avoid duplicate source creation

---

src/util.js

Currently we fetch a TileJSON as soon as we have a `url` in the source definition. But Esri style docs sometimes contain both a `url` and `tiles`. In this case, we do not need to fetch the TileJSON, and can use the information from the source directly.

Avoid unnecessary TileJSON fetch

---

src/apply.js
src/util.js

This makes use of `Object.assign` instead of importing `assign` from the `ol/obj.js` module.
See openlayers/openlayers#13888.

Use Object.assign

---

README.md
examples/apply-layergroup.js
examples/data/geojson-wms.json
examples/index.html
examples/olms-group.js
src/apply.js
test/apply.test.js

Overall applying to layer group went as planned. I have three questions, marked in code with `???` comments. 
1. `// ??? Rename mapOrGroupOrLayer` Not sure readability or consistency is better here
2. `// ??? could apply to first layer` I might just need the weekend to think this over, but given background is often the first style layer processed, I can't simply apply to the first actual layer in the group
3. ` // ??? A group wouldn't have a reference` I assume this code still important even when used within a group, but not sure how to reference back to the map view when you start at a layer group

Apply to Layer Groups

---

src/apply.js
test/apply.test.js

Currently, the new way to render background fails on vector tile layers because of clipping in the OpenLayers renderer. By applying the background after other content, this can be avoided.

Render background after content so it doesn't get clipped away

---

src/apply.js
test/apply.test.js
test/fixtures/wms.json

Currently it is barely impossible to override a raster layer's opacity by using `layer.setOpacity()` in OpenLayers.
This pull request makes it so when no `raster-opacity` paint property is set on the Mapbox raster layer, `layer.setOpacity() can always be used, and its value won't get overridden on zoom changes. When `raster-opacity` is set, it can be changed in the Mapbox Style object, and will be applied on the next render cycle.
Fixes #675.

Make raster-opacity less sticky

---

.gitignore
.idea/workspace.xml
src/mapbox.js
src/util.js

An issue occurs when trying to add a mapbox style with satellite. 
A lot of request are done to localhost/a, localhost/b, .... 
Also when the style includes a v8 of streets the tiles are not loaded. I compared how mapbox reads the implementation for the tiles and it just perform a call to api.mapbox.com instead of tiles.mapbox.com

fix: mapbox satellite and streets v8

---

src/apply.js
src/shaders.js
test/apply.test.js
test/fixtures/raster-dem.json

This pull request adds basic support for `raster-dem` sources with layers of type `hillshade`. The supported layer properties are
* `hillshade-exaggeration`
* `hillshade-illumination-direction`
Fixes #714.

Add support for raster-dem sources with hillshade layers

---

src/apply.js
test/apply.test.js
test/fixtures/geojson-wfs.json

This pull request applies the minimum of all layer minzooms for geojson layers to the OpenLayers layer.
This avoids excessive data downloads from geojson sources that have `{bbox-epsg-3857}` in the url.

Limit minzoom for geojson layers

---

src/util.js
test/apply.test.js

Currently, transformRequest is only called for vector sources when inline TileJSON is used. This pull request makes it also work for raster sources.

Call transformRequest for raster sources with inline TileJSON

---

src/apply.js

The `getLayer()` and `getSource()` functions all work with layer groups already, it's just not documented.
For `getLayers()`, this pull request also changes the function to use `#getLayers()` instead of `#getAllLayers()`. With this change, it works for layer groups too, but won't find Mapbox layers across layer groups any more, which was a bug.

Update docs getLayers() to also work with layer groups

---

src/util.js
test/util.test.js

fetchResource() caches pending requests (or rather the Promises of their
responses) to prevent repeated calls for the same resource. If a
response is not pending then the generated Request object may be
returned via the metadata parameter, but before this commit then if the
response was already pending the Request object was never returned in
this way. This led to problems in getTileJson() where it is expected
(required) that the request has been set.
With this PR then not just the Promises of the responses but also the
original Request objects are cached so that the request parameter can
also be set in the metadata object when a pending response is returned.
The problem was noticed while trying to use apply() in parallel on two
group layers using each a different style URL, which however …

bugfix: pending requests metadata

---

src/stylefunction.js

When an OpenLayers version that contains https://github.com/openlayers/openlayers/pull/14400 is used, labels will now be repeated on long line segments according to the `symbol-spacing` layout property.

Add support for labels with symbol-spacing

---

README.md
examples/esri-4326.js
examples/index.html
src/apply.js
test/apply.test.js

This pull request adds support for projections, using the new `projection` option. It requires the used projection to be set up properly in OpenLayers. The projection extent determines the tile grid origin and resolutions for all layer sources.
To make configuration easier, projections with units other than meters now also work out of the box, because the style resolutions will be adjusted for the different units.

Support projections

---

src/apply.js

Currently, when a raster source is used more than once in a map, the `mapbox-layers` metadata field will incorrectly list all the layers that use the source, instead of just the one that is actually represented by the OpenLayers layer.
This pull request fixes that, i.e. for raster layers, `mapbox-layers` will always only contain a single entry.

Fix 'mapbox-layers' metadata for raster layers

---

examples/data/geojson-inline.json
src/stylefunction.js

This pull request adds support for the `icon-halo-color` and `icon-halo-width` `paint` properties. The implementation uses the `shadowColor` and `shadowBlur` properties of the `CanvasRenderingContext2D` API.

Add support for icon-halo-color and icon-halo-width

---

README.md
src/apply.js
src/index.js
src/stylefunction.js
src/util.js
test/apply.test.js
test/stylefunction.test.js

This pull request adds new functions for interacting with Mapbox Layer objects:
* `getMapboxLayer(mapOrLayerGroup, layerId)` to retrieve a layer from the Mapbox Style object
* `addMapboxLayer(mapOrLayerGroup, layer)` to add a Mapbox Layer object to the Mapbox Style object
* `updateMapboxLayer(mapOrLayerGroup, layer)` to update a Mapbox Layer object and re-render the map

New API for working with layer style objects

---

CHANGELOG.md
examples/data/geojson-wfs.json
src/apply.js
test/apply.test.js

Previously, the `{bbox-epsg-3857}` and `{bbox-epsg-[custom projection srs code]}` template replacement included the projection's SRS identifier, e.g. `1234,4567,4321,7654,EPSG:9876`. Now, the template replacement just includes the bounding box. This means that e.g. WFS source URLs need to be changed in the Mapbox style.
If you previously had a source definition like
```json
{
"type": "geojson",
"data": "https://ahocevar.com/geoserver/wfs?service=WFS&version=1.1.0&request=GetFeature&typename=osm:water_areas&outputFormat=application/json&srsname=EPSG:4326&bbox={bbox-epsg-3857}"
}
```
you have to change it to
```json
{
"type": "geojson",
"data": "https://ahocevar.com/geoserver/wfs?service=WFS&version=1.1.0&request=GetFeature&typename=osm:water_areas&outputFormat=application/json&srsname=EPSG: …
```

Remove SRS identifier from geojson BBOX template replacement

---

src/index.js

This adds the missing export `removeMapboxLayer` to the exports of index.js

add `removeMapboxLayer` to exports

---

src/stylefunction.js
src/util.js
test/apply.test.js

`updateMapboxLayer()` did not work as expected, because the function and filter caches were never cleared. Now that they are, a flaw with `renderTransparent()` was revealed, which is also fixed with this pull request.

Fix updateMapboxLayer by fixing function and filter cache management

---

src/apply.js

This fixes a potential problem with the OpenLayers tile queue (and cache): currently, Vector Tile Sources created from TileJSON by ol-mapbox-style do not have a source key, because they do not have a url set.

Ensure sources have a unique key

---

src/stylefunction.js
test/stylefunction.test.js

This fixes #874, preventing the icon-offset to change after re-applying the same style.
This is opened asa Draft-PR, as the test does not seem to fail in the current main, most likely because the rendering is not triggered correctly.

Fix icon offset flip

---

src/apply.js
test/apply.test.js

Currently, when using the `projection` option, vector data would be transformed from EPSG:4326, instead of leaving the coordinates untouched, because the GeoJSON format is not configured with the provided `projection` as its `dataProjection`. This pull request fixes that.

Set projection from projection option as GeoJSON dataProjection

---

README.md
examples/maptiler-hillshading.js
src/stylefunction.js
src/text.js
test/apply.test.js
test/text.test.js

This pull request implements the changes suggested in https://github.com/openlayers/ol-mapbox-style/issues/698#issuecomment-1473903973.
Fixes #698.

Flexible font handling without Google Fonts default

---

README.md
src/index.js
src/stylefunction.js
test/stylefunction.test.js

This pull request adds a function that can help existing applications to live without `recordStyleLayer(true)`, and to create legends more easily.
The function calls the layer's style function internally, but only evaluates the style for a single Mapbox layer.

Add getStyleForLayer() function

---

README.md

The prefix for the webfonts property in the metadata is `ol:`, not `ol-`.

Fix metadata prefix in README

---

README.md
src/apply.js
src/util.js
test/finalizeLayer.test.js
test/util.test.js

This pull request removes the restriction that `addMapboxLayer()` can only add a layer when it has the same source as an adjacent layer.
Fixes #917.

Create layer for added mapbox layer

---

examples/index.html
examples/sdf-sprites.js
src/stylefunction.js
src/util.js

This PR adds support for SDF sprites.
Though not very well documented, the mapbox-gl-js has support SDF sprites for years.
Such sprites contain "distances" instead of the regular color information:
In such cases, the `sprite.json` has a `sdf: true` on each image.
The benefits of the SDF sprites include better scalability and ability to recolor the images nicely.
We would like to start using SDF sprites in MapTiler in the future, but still remain compatible with the `ol+ol-mapbox-style` stack, so this PR adds a basic support for the SDF sprites.
- In case of regular icons, the whole sprite image atlas is "unSDFied" once when it's first needed and then used the regular way (color tinting works the same as before)
- In case of halo, only the specific icon is "unSDFied" with proper coloring …

Add support for SDF sprites

---

src/apply.js

The documentation about when `applyStyle()` modifies a source configured with the provided `layer` is confusing.
This pull request attempts to clarify that.

Clarify source update behavior

---

README.md
package-lock.json
package.json
rollup.config.js
src/MapboxVectorLayer.js
src/index.js
webpack.config.examples.cjs

By getting rid of buble transpilation, we can now export the new MapboxVectorLayer with the index module.

Export MapboxVectorLayer with index module

---

package-lock.json
package.json

To allow deduping of ol, use the latest dev version, but also allow 7.x.

Use ol@dev

---

package-lock.json
package.json

Following @tschaub's [comment](https://github.com/openlayers/openlayers/pull/15042#discussion_r1306148780), this pull request makes `ol` a peer dependency of `ol-mapbox-style`.

Make ol a peer dependency

---

README.md
src/apply.js
src/index.js
test/util.test.js

Fixes #1008.
**updateMapboxSource**(`mapOrGroup`, `id`, `mapboxSource`): `Promise`&lt;`Source`>
Updates a Mapbox source object in the style. The according OpenLayers source will be replaced
and the map will be re-rendered.
| Name           | Type                  | Description                                        |
| :------------- | :-------------------- | :------------------------------------------------- |
| `mapOrGroup`   | `Map` \| `LayerGroup` | The Map or LayerGroup `apply` was called on.       |
| `id`           | `string`              | Key of the source in the `sources` object literal. |
| `mapboxSource` | `any`                 | Mapbox source object.                              |
`Promise`&lt;`Source`>
Promise that resolves when the source has been updated.

New 'updateMapboxSource()' utility function

---

README.md
src/apply.js
src/stylefunction.js
src/util.js
test/MapboxVectorLayer.test.js
test/apply.test.js
test/applyStyle.test.js
test/util.test.js

This pull request enables `transformRequest()` to return a `Promise` resolving to a `Request` or url `string`, instead of just a `Request` or an `url` string. This allows users that need to add auth headers to obtain those headers asynchronously:
```js
transformRequest: async (url, type) => {
return new Request(
url,
{
headers: await getAuthHeaders()
}
);
}

Accept Promise as return type for transformRequest

---

src/stylefunction.js

This adds the missing scale property on Icon when using non-sprite images.

Apply icon-size (scale) for imageElement icons

---

src/apply.js
src/util.js

This pull request fixes a problem where a layer minResolution or maxResolution will be set to NaN when the lowest or highest zoom of a Mapbox layer for an OpenLayer layer is a fractional zoom.

Handle fractional zooms for layer min/maxResolution properly

---

src/stylefunction.js

Previously the `default` from the property spec for `line-color` was not being applied because of the clause `'line-color' in paint`
This PR fixes that, which means the following layer style will show a line (in line with maplibre/mapbox)
```json
{
"id": "test",
"type": "line",
"source": "lines",
"layout": {},
"paint": {}
}
```

Allow default `line-color` when property not present

---

src/apply.js

This PR is a fix to use the default from the spec for the `background-color`. The following now results in a `#000000` background as per the spec.
```json
{
"id": "background",
"type": "background",
"paint": {}
}
```

Allow `background-color` to use default from spec

---

src/stylefunction.js

Added support for `circle-translate`
Screenshot of OpenLayers on **left** and MapLibre (via Maputnik) on **right** 
With the following layers added to the style from <https://raw.githubusercontent.com/openlayers/ol-mapbox-style/dab4ad81d99d317e20e101228071de0f9745c801/examples/data/geojson-inline.json>
```json
[
{
"source": "points",
"type": "circle",
"id": "points1",
"layout": {
},
"paint": {
}
},
{
"source": "points",
"type": "circle",
"id": "points2",
"layout": {
},
"paint": {
"circle-translate": [5, 5],
"circle-color": "red"
}
},
{
"source": "points",
"type": "circle",
"id": "points3",
"layout": {
},
"paint": {
"circle-translate": [10, 10],
"circle-color": "green"
}
},
{
"source": "points",
"type": "circle",
"id": "points4",
"layout": {
},
"paint": {
"circle-translate": [15, 15], …
```

Added support for `circle-translate`

---

src/apply.js

Previous to this change a style with a `heatmap` layer type would "throw" crashing the app. We now just `console.debug` with
```
[ol-mapbox-style] layers[1].type "heatmap" not supported
```
Reasons for `console.debug` instead of console warn/log, is that `console.debug` doesn't show up in the console by default. You have to enable verbose logging in the web inspector.
This also has the same behaviour as other unsupported styling rules, for example [icon-pitch-alignment](https://docs.mapbox.com/style-spec/reference/layers/#layout-symbol-icon-pitch-alignment)

Don't throw on unsupported `heatmap` layer type instead show helpful debug info

---

README.md
src/stylefunction.js

When an `icon-offset` is set, it will be rendered incorrectly when `icon-size` is also set. This is because of the translation into OpenLayers'  `displacement`, which is applied to the scaled icon.

Fix icon-offset when icon-size is also set

---

src/stylefunction.js
test/stylefunction.test.js

Zero width text halo should be treated as no text halo

Zero text halo should be no halo

---

README.md
src/stylefunction.js

`text-transform` appears to be the last remaining property that does not work for context computed values. This pull request fixes that.

Compute value of text-transform

---

src/apply.js
src/util.js
test/apply.test.js

This should have been fixed with #1032, but it did not. The resulting resolutions were still `NaN`.

Properly handle fractional layer minzoom and maxzoom

---

src/apply.js
test/MapboxVectorLayer.test.js
test/apply.test.js
test/applyStyle.test.js

This pull request fixes a regression introduced by #1121, with the smaller adjustments for `maxResolution` to avoid glitches with projections that have small resolution differences between zooms. To avoid these glitches, instead of adjusting the resolution to make `minZoom` inclusive, we now adjust the `minZoom` directly.

Make minZoom inclusive by zoom instead of resolution

---

examples/_template.html

Because of security issues outlined in <https://dev.to/snyk/polyfill-supply-chain-attack-embeds-malware-in-javascript-cdn-assets-55d6>
Removed because no longer required, browser support is good enough now

Remove polyfill io

---

src/stylefunction.js

Currently, when using `"symbol-placement": "line"` and `"icon-rotation-alignment": "map"`, the angle of the icon is computed in ol-mapbox-style, as we know the location of the icon placement but not the corresponding line segment information. So the computation first tries to determine on which line segment the icon is located, then computes the slope of this segment and uses that as the rotation of the icon.
However, the algorithm used to determine on which segment is the icon is too simplistic: it simply takes the first segment for which the icon is inside the bounding box. However, there is no guarantee that this segment is the correct one and it is quite easy to construct a counter-example giving a wrong rotation angle: 
while it should be 
This pull request proposes to replace this …

more precise angle computation

---

examples/pmtiles.js
package-lock.json
package.json

With the [pmtiles-protocol](https://npmjs.com/package/pmtiles-protocol) package, consuming PMTiles gets much easier.

Use the pmtiles-protocol package for the pmtiles example

---

src/stylefunction.js

Until now, the `text-keep-upright` parameter in the Mapbox Style specification was ignored, as OpenLayers was automatically keeping the labels upright and did not expose an option to control it. Now that the `keepUpright` parameter is available on `ol/style/Text`, this PR uses it to cover `text-keep-upright`.
This is a follow-up to #1206 now that the cleaner solution is available.

Use the new keepUpright parameter in OpenLayers

---

.eslintrc
CHANGELOG.md
eslint.config.js_
package-lock.json
package.json
rollup.config.js
src/apply.js
src/stylefunction.js
test/karma.conf.cjs
test/stylefunction-utils.test.js
webpack.config.examples.cjs

I'm putting this up for discussion, as an alternative to #939.
The one thing that makes me hesitant to make this change is that I don't know what the plans are for Maplibre to stick with or depart from the Mapbox style spec. If someone from @maplibre, maybe @birkskyum, could comment on that, it would make the decision easier.

Use maplibre instead of mapbox style spec

---

package.json

This pull request points to the types for the exports, because we no longer have an ESM bundle since #940.

Add types for exports

---

examples/pmtiles.js
package-lock.json
package.json
src/apply.js
src/mapbox.js
src/util.js
test/util.test.js

This pull request adds a huge improvement to the `transformRequest()` option: the function may now also return a Response or a Promise resolving to a Response. This means: no more Object URLs for anything that can be `fetch`ed! The modified `pmtiles.js` example shows how to make use of it.

Accept Response and Promise<Response> as transformRequest return

---

package.json

Since dist/index.js no longer exists, values for browser and module needs to be updated accordingly. Without this we get errors when trying to import the package as a module.

Update package.json to point to src/index.js

---

src/apply.js

Both functions can also be called with a `LayerGroup` as first argument.

Fix argument types for setFeatureState() and getFeatureState()

---

src/stylefunction.js

Fixes #1273.
Instead of failing on invalid filters, we now only print a warning to the console.

Warn on filter errors, instead of failing

---

CHANGELOG.md
src/MapboxVectorLayer.js
src/apply.js
src/stylefunction.js
test/util.test.js

This pull request fixes a name collision with styles that have features with a property named `layer`, which is the internally used `layerName` property created by the `MVT` format.
This name collision was e.g. observed in the mapbox-streets-v12 map.

Try to avoid layerName collisions

---

src/text.js

This pull request fixes an issue where line breaks in texts may be inserted incorrectly or missing. That is when text width measurements were done before the correct font was loaded. The measure cache was never cleared.
This pull request ensures that the text measurements are cleared when new fonts are loaded, so text will be redrawn with the correct font *and* the correct line breaks when the correct font has finished loading.

Clear text measure cache when loaded fonts have changed

---

src/apply.js
src/stylefunction.js
test/applyStyle.test.js

By not assuming `mvt:layer`, we can avoid surprises when the source's format uses a different `layerName`.
See https://github.com/openlayers/openlayers/issues/17014

Respect the 'layerName' property of the source format
